stages:
    - build-prerequisite-containers
    - build-code
    - babel
    - deploy

build-code:
    stage: build-code
    dependencies:
    - build-elm
    script:
     - cd code && make
    artifacts:
      paths:
        - code/src/*.css
        - code/js
        - code/src/*.html
        - code/src/*.svg
        - code/img/*.png

build-babel:
    stage: build-prerequisite-containers
    script:
    - cd babel && make

build-elm:
    stage: build-prerequisite-containers
    script:
    - cd elm && make

babel:
    stage: babel
    dependencies:
    - build-code
    - build-babel
    script:
    - docker run -t --rm -v `pwd`:/work -w /work -u $(id -u):$(id -g) babel
    - mv code/js/cytoutils.babel.js code/js/cytoutils.js
    artifacts:
      paths:
        - code/src/*.css
        - code/js
        - code/src/*.html
        - code/src/*.svg
        - code/img/*.png

pages:
  stage: deploy
  dependencies:
     - babel
  script:
       - mkdir public
       - mv code/src/*.css public/
       - mv code/js public/
       - mv code/src/*.html public/
       - mv code/src/*.svg public/
       - mv code/img/*.png public/
       - mv public/graphTool.html public/index.html
       - rm -rf public/graphTool.html
  artifacts:
        when: on_success
        paths:
        - public
  only:
  - master
