stages:
    - build
    - babel
    - deploy

build:
    stage: build
    script:
     - cd code && make
    artifacts:
      paths:
        - code/src/*.css
        - code/src/js
        - code/src/*.html
        - code/src/*.svg
        - code/src/*.png

build-babel:
    stage: build
    script:
    - cd babel && make

babel:
    stage: babel
    dependencies:
    - build
    script:
    - docker run -t --rm -v `pwd`:/work -w /work -u $(id -u):$(id -g) babel
    - mv code/src/js/cytoutils.babel.js code/src/js/cytoutils.js
    artifacts:
      paths:
        - code/src/*.css
        - code/src/js
        - code/src/*.html
        - code/src/*.svg
        - code/src/*.png

pages:
  stage: deploy
  dependencies:
     - babel
  script:
       - mkdir public
       - mv code/src/*.css public/
       - mv code/src/js public/
       - mv code/src/*.html public/
       - mv code/src/*.svg public/
       - mv code/src/*.png public/
       - mv public/graphTool.html public/index.html
       - rm -rf public/graphTool.html
  artifacts:
        when: on_success
        paths:
        - public
  only:
  - master
