sudo: required
services:
- docker

before_install:
- echo "Before install"

before_script:
- cd babel && make && cd ..
- cd elm && make && cd ..

script:
- echo "Script"
- cd code && make && cd ..
- docker run -t --rm -v $(pwd):/work -w /work -u $(id -u):$(id -g) babel
- mv code/js/cytoutils.babel.js code/js/cytoutils.js

after_script:
- echo "After script"

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo "Success" ; fi

notifications:
email: true
