sudo: required
services:
- docker

before_install:
- echo "Before install"

before_script:
- echo "Before script"

script:
- echo "Script"
- cd code && make && cd ..


after_script:
- echo "After script"

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo "Success" ; fi

notifications:
email: true
